name = "wagminew"
compatibility_date = "2023-05-21"

# Next.js configuration for Cloudflare Pages
[build]
command = "npm run build"

# Use the out directory for static site generation with Next.js
[site]
bucket = "out"

# For Cloudflare Pages
pages_build_output_dir = "out"

[env.production]
workers_dev = true

[build.environment]
NODE_VERSION = "18"
